/*
 event listeners*/

document.addEventListener('DOMContentLoaded', () => {
  const auditBtn = document.getElementById('auditBtn');
  const resetBtn = document.getElementById('resetBtn');
  const copyBtn  = document.getElementById('copyBtn');
  const input    = document.getElementById('urlInput');

  auditBtn.addEventListener('click', startAudit);
  resetBtn.addEventListener('click', resetAudit);
  copyBtn.addEventListener('click', copyReport);

  input.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') startAudit();
  });
});

async function startAudit() {
  const raw = document.getElementById('urlInput').value;

  if (!raw.trim()) {
    const input = document.getElementById('urlInput');
    input.style.borderColor = 'var(--danger)';
    setTimeout(() => { input.style.borderColor = ''; }, 1500);
    return;
  }

  const url = normalizeUrl(raw);

  document.getElementById('auditBtn').disabled = true;
  resetLoaderSteps();
  showLoader();

  await animateLoaderSteps();

  hideLoader();

  const score  = computeScore(url);
  const issues = pickItems(ISSUES, url, 5);
  const recs   = pickItems(RECOMMENDATIONS, url + 'r', 3);

  showResults(url, score, issues, recs);

  document.getElementById('auditBtn').disabled = false;
}

function resetAudit() {
  document.getElementById('results').classList.add('hidden');
  document.getElementById('urlInput').value = '';
  window.scrollTo({ top: 0, behavior: 'smooth' });
  setTimeout(() => { document.getElementById('urlInput').focus(); }, 600);
}

function copyReport() {
  const url    = document.getElementById('siteUrl').textContent;
  const score  = document.getElementById('scoreNum').textContent;
  const issues = [...document.querySelectorAll('.issue-body h3')]
    .map(h => '- ' + h.textContent)
    .join('\n');

  const report = [
    'CheckMate - AI Readiness Audit',
    '',
    `URL:   ${url}`,
    `Score: ${score}/100`,
    '',
    'Issues Found:',
    issues,
    '',
    'Generated by CheckMate'
  ].join('\n');

  navigator.clipboard.writeText(report).then(() => {
    const btn = document.getElementById('copyBtn');
    btn.textContent = 'Copied!';
    setTimeout(() => { btn.textContent = 'Copy Report'; }, 2000);
  });
}
